stages:
  data_preparation:
    cmd: python prepare_data.py --input_path ../data/census.csv --output_path ../data
    deps:
    - ../data/census.csv
    - pipeline_components.py
    - prepare_data.py
    params:
    - data.target
    - data.test_size
    - seed
    outs:
    - ../data/fitted_data_pipeline.joblib
    - ../data/test_clean_census.csv
    - ../data/train_clean_census.csv
    - ../data/train_processed_census.csv
  modelling:
    cmd: python train_model.py --input_path_train ../data/train_clean_census.csv --output_path
      .. --pipe_path ../data/fitted_data_pipeline.joblib --variable sex --metrics_path
      ../data/slice_output.txt --input_path_test ../data/test_clean_census.csv
    deps:
    - ../data/train_clean_census.csv
    - ../data/test_clean_census.csv
    - pipeline_components.py
    - train_model.py
    params:
    - data.target
    - model
    outs:
    - ../model.joblib
    - ../data/slice_output.txt